### ISSUE TITLE
small typo in getUserAlbums block

### ISSUE THREAD

**Issue by davidnoah** [RapidSoftwareSolutions/Marketplace-FacebookGraphAPI-Package#1]
the "profile_id" parameter is misspelled as "prodile_id" in the getUserAlbums block
<img width="458" alt="screen shot 2017-01-06 at 4 37 17 pm" src="https://cloud.githubusercontent.com/assets/16233878/21737517/6c885232-d42e-11e6-882a-38b2907d160c.png">

**Comment by Acceptto** [comment]
@davidnoah thanks man. Fixed.
